name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - ricardoquesada
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Bluepad32 Version
      description: What version of our software are you running?
      options:
        - I don't know
        - latest from develop branch
        - 4.0-beta2
        - 4.0-beta1
        - 4.0-beta0
        - 3.10.3
        - 3.10.2
        - 3.10.1
        - 3.10.0
        - 3.9.0
        - 3.8.3
        - 3.8.2
        - 3.8.1
        - 3.8.0
        - 3.7.3
        - 3.7.2
        - 3.7.1
        - 3.7.0
        - Other
    validations:
      required: true
  - type: textarea
    id: version-custom
    attributes:
      label: Bluepad32 version custom
      description: Bluepad32 version custom
      value: "Example: Using Git develop branch commit hash #xxxxxxx"
  - type: dropdown
    id: platforms
    attributes:
      label: Bluepad32 Platform
      description: What Bluepad32 platform are you using?
      options:
        - Arduino IDE
        - Arduino ESP-IDF
        - Arduino + NINA
        - CircuitPython + AirLift
        - ESP-IDF
        - Pico SDK
        - Posic (Linux, macOS)
        - Unijoysticle
        - MightyMiggy
        - Other
  - type: textarea
    id: platforms-custom
    attributes:
      label: Platform version
      description: Which Platform version?
      value: "E.g: Arduino IDE 2.1.0, or ESP-IDF v4.4.4, or CircuitPython 8.0.0, etc."
  - type: textarea
    id: controller
    attributes:
      label: Controller
      description: Which controller are you using ?
      value: "Xbox Wireless 1708 using firmware 5.15.1923. Link to controller: https://example.com"
  - type: dropdown
    id: mcu
    attributes:
      label: Microcontroller
      description: What microcontroller are you using?
      options:
        - ESP32
        - ESP32-S3
        - ESP32-C3
        - Pico W
    validations:
      required: true
  - type: textarea
    id: mcu-custom
    attributes:
      label: Microcontroller board
      description: Which board/module are you using?
      value: "ESP32-S3-WROOM1 DevKit from Lolin. This is the store URL: https://example.com"
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: sketch
    attributes:
      label: Relevant sketch
      description: Please copy and paste the sketch that reproduces the bug. This will be automatically formatted into code, so no need for backticks.
      render: shell
