name: Build with ESP-IDF v5.5

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-platforms:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [plat_unijoysticle, plat_mightymiggy, plat_nina, plat_airlift]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Patch BTStack
      shell: bash
      run: cd external/btstack && git apply ../patches/*.patch

    - name: Build ${{ matrix.platform }}
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.5
        target: esp32
        path: 'src'
        command: 'idf.py -B build_${{ matrix.platform }} -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.${{ matrix.platform }}" build'

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32, esp32s3, esp32c3, esp32c6, esp32h2, esp32c5]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Patch BTStack
      shell: bash
      run: cd external/btstack && git apply ../patches/*.patch

    - name: Example ${{ matrix.target }} build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.5
        target: ${{ matrix.target }}
        path: 'examples/esp32'
        command: "idf.py set-target ${{ matrix.target }} && idf.py build"
