name: Build with Pico SDK

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board: [pico_w, pico2_w]
        btstack_source: [pico_sdk, bluepad32_submodule]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Patch BTStack
        if: matrix.btstack_source == 'bluepad32_submodule'
        shell: bash
        run: cd external/btstack && git apply ../patches/*.patch

      - name: Checkout pico-sdk/master
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: master
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{ github.workspace }}/pico-sdk
        run: git submodule update --init

      - name: Create build folder
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}/examples/pico_w/build"
          mkdir -p "${{ github.workspace }}/examples/pico_w/build"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install tzdata pkg-config make cmake gcc-arm-none-eabi

      - name: Configure CMake (Pico SDK BTstack)
        if: matrix.btstack_source == 'pico_sdk'
        shell: bash
        working-directory: ${{ github.workspace }}/examples/pico_w/build
        run: PICO_SDK_PATH=../../../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPICO_BOARD=${{ matrix.board }}

      - name: Configure CMake (Bluepad32 Submodule BTstack)
        if: matrix.btstack_source == 'bluepad32_submodule'
        shell: bash
        working-directory: ${{ github.workspace }}/examples/pico_w/build
        run: PICO_SDK_PATH=../../../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPICO_BOARD=${{ matrix.board }} -DBTSTACK_ROOT=${{ github.workspace }}/external/btstack

      - name: Build
        working-directory: ${{ github.workspace }}/examples/pico_w/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE --parallel $(nproc)
